# Generated by Django 6.1.1 on 2026-09-29 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('rutas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('ADM', 'Administrador'), ('OPE', 'Operador'), ('COU', 'Courier')], default='OPE', max_length=3)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('estado', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Déjalo vacío para generarlo automáticamente.', max_length=20, unique=True, verbose_name='Código de encomienda')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso (kg)')),
                ('volumen_cm3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volumen (cm³)')),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], default='PE', max_length=2)),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo de envío (S/)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_est', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de entrega')),
                ('fecha_entrega_real', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega real')),
                ('observaciones', models.TextField(blank=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_recibidos', to='clientes.cliente')),
                ('empleado_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_registradas', to='envios.empleado', verbose_name='Empleado que registró')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_enviados', to='clientes.cliente')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], max_length=2)),
                ('estado_nuevo', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], max_length=2)),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to='envios.empleado')),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='envios.encomienda')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
