# Generated by Django 6.1.1 on 2026-09-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio base (S/)')),
                ('dias_estimados', models.PositiveIntegerField(default=1, verbose_name='Días estimados')),
                ('estado', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['origen', 'destino'],
            },
        ),
    ]
