# Generated by Django 6.1.1 on 2026-09-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carné de extranjería')], default='DNI', max_length=3, verbose_name='Tipo de documento')),
                ('nro_doc', models.CharField(max_length=15, unique=True, verbose_name='Nro. documento')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('estado', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
